name: Build Theme
'on':
  push:
    branches:
    - main
    - develop
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install gitversion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: 5.x
    - id: gitversion
      name: Use gitversion
      uses: gittools/actions/gitversion/execute@v3.0.0
      with:
        useConfigFile: true
        configFilePath: ./gitversion.yml
    - name: Display version
      run: 'echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"'
  build-firefox:
    needs:
    - version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Bump manifest version
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: '"version": ".+"'
        replace: '"version": "${{ needs.version.outputs.version }}"'
        regex: true
    - run: zip theme.xpi manifest.json
    - uses: actions/upload-artifact@v4
      with:
        name: firefox-xpi
        path: ./theme.xpi
  build-chrome:
    needs:
    - version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Bump manifest version
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: '"version": ".+"'
        replace: '"version": "${{ needs.version.outputs.version }}"'
        regex: true
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: python rewrite-manifest.py
    - run: zip theme.zip chrome/
    - env:
        EXTENSION_KEY: ${{ secrets.CHROME_SIGNING_KEY }}
      uses: emilymclean/pack-chromium-extension-action@v1.0.3
      with:
        input-folder: chrome
        output-file: theme.crx
    - uses: actions/upload-artifact@v4
      with:
        name: chrome-zip
        path: ./theme.zip
    - uses: actions/upload-artifact@v4
      with:
        name: chrome-crx
        path: ./theme.crx
  release:
    permissions:
      contents: write
    needs:
    - version
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create tag for release
      uses: rickstaa/action-create-tag@v1
      with:
        tag: v${{ needs.version.outputs.version }}
    - id: create_release
      name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ needs.version.outputs.version }}
        name: Release ${{ needs.version.outputs.version }}
        draft: false
        prerelease: ${{ github.ref != 'refs/heads/main' }}
  publish-firefox-release:
    permissions:
      contents: write
    needs:
    - version
    - release
    - build-firefox
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: firefox-xpi
        path: ./
    - name: Upload Artifact to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./theme.xpi
        asset_name: firefox-witchy-hazel-v${{ needs.version.outputs.version }}.unsigned.zip
        asset_content_type: application/zip
    - name: Upload Artifact to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./theme.xpi
        asset_name: firefox-witchy-hazel-v${{ needs.version.outputs.version }}.unsigned.xpi
        asset_content_type: application/zip
  publish-chrome-release:
    permissions:
      contents: write
    needs:
    - version
    - release
    - build-chrome
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
        - chrome-crx
        - chrome-zip
        include:
        - name: chrome-crx
          file-name: theme.crx
          extension: crx
          content-type: application/x-chrome-extension
        - name: chrome-zip
          file-name: theme.zip
          extension: zip
          content-type: application/zip
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: ./
    - name: Upload Artifact to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./${{ matrix.file-name }}
        asset_name: chrome-witchy-hazel-v${{ needs.version.outputs.version }}.unsigned.${{ matrix.extension }}
        asset_content_type: application/zip
